version: "2.4"
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root